groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::reduce_transparency
        - osxdefaults::disable_auto-correct
        - osxdefaults::dark-mode
attributes:
    git:
        name: Brian Green
        email: brian.green@lightspeedvt.com
    authorization:
        sudo:
            users:
                - briangreen
            passwordless: true
            include_sudoers_d: true
