groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
attributes:
    git:
        name: Carl Esperance
        email: carlo.esperance@lightspeedvt.com
    authorization:
        sudo:
            users:
                - carloe
            passwordless: true
            include_sudoers_d: true
