groups:
    - designer
recipes:
    mac_os_x:
        - sudoalt::default
attributes:
    git:
        name: Dan Scott
        email: dan.scott@lightspeedvt.com
    authorization:
        sudo:
            users:
                - dans
            passwordless: true
            include_sudoers_d: true
