groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
attributes:
    git:
        name: Diana Rosas
        email: diana.rosas@lightspeedvt.com
    authorization:
        sudo:
            users:
                - dianar
            passwordless: true
            include_sudoers_d: true
