groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
attributes:
    git:
        name: Derick Brown
        email: derick.brown@lightspeedvt.com
    authorization:
        sudo:
            users:
                - edit11
            passwordless: true
            include_sudoers_d: true
