groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
attributes:
    git:
        name: Vince Bratton
        email: vince.bratton@lightspeedvt.com
    authorization:
        sudo:
            users:
                - vince
            passwordless: true
            include_sudoers_d: true
